package com.treble.feasimulation.service;

import com.treble.feasimulation.model.*;
import com.treble.feasimulation.solver.BeamSolver;
import com.treble.feasimulation.solver.PlaneStressResult;
import com.treble.feasimulation.solver.TrussSolver;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/**
 * Utilities to convert the model and results between display units and SI units.
 *
 * Policy (Phase 3):
 * - Geometry (node/vertex coordinates) is scaled by metersPerUnit to SI.
 * - Material properties are assumed SI already (Pa, kg/m^3, thickness in meters) — unchanged.
 * - Loads are assumed SI already (N, N/m) — unchanged.
 * - Elements that rely on geometry (e.g., TriangularElement) are generated by solvers; we only
 *   convert their geometry for display when needed.
 */
public final class UnitConverter {
    private UnitConverter() {}

    /** Create a deep-copied SI-normalized model from the source model. */
    public static FEAData toSI(FEAData src, UnitSettings units) {
        double s = units.getMetersPerUnit();
        FEAData dst = new FEAData();

        // Materials: assume SI already
        for (Material m : src.getMaterials()) dst.addMaterial(m);

        // Nodes: scale coordinates
        Map<Integer, Integer> idToNewId = new HashMap<>();
        for (Node n : src.getNodes()) {
            Node nn = (n instanceof TrussNode)
                    ? new TrussNode(n.getId(), n.getX() * s, n.getY() * s)
                    : new Node(n.getId(), n.getX() * s, n.getY() * s);
            dst.addNode(nn);
            idToNewId.put(n.getId(), nn.getId());
        }

        // Elements: copy as-is (areas/inertias presumed SI), node IDs preserved
        for (Element e : src.getElements()) {
            if (e instanceof BeamElement be) {
                dst.addElement(new BeamElement(be.getId(), be.getNodeStartId(), be.getNodeEndId(), be.getMaterialId(), be.getArea(), be.getInertia()));
            } else if (e instanceof TrussElement te) {
                dst.addElement(new TrussMember(te.getId(), te.getNodeStartId(), te.getNodeEndId(), te.getMaterialId(), te.getArea()));
            } else {
                dst.addElement(e); // fallback
            }
        }

        // Supports: unchanged (node ids identical)
        for (Support spt : src.getSupports()) dst.addSupport(new Support(spt.getId(), spt.getNodeId(), spt.getType()));

        // Point loads: SI already (N), unchanged
        for (PointLoad pl : src.getPointLoads()) dst.addPointLoad(new PointLoad(pl.getId(), pl.getNodeId(), pl.getFx(), pl.getFy(), pl.getMoment()));

        // Polygon regions: scale vertices
        for (PolygonRegion pr : src.getPolygonRegions()) {
            List<PolygonRegion.Vertex> verts = new ArrayList<>();
            for (PolygonRegion.Vertex v : pr.getVertices()) {
                verts.add(new PolygonRegion.Vertex(v.getX() * s, v.getY() * s));
            }
            dst.addPolygonRegion(new PolygonRegion(pr.getId(), verts, pr.getMaterialId()));
        }

        // Edge supports: unchanged indices
        for (EdgeSupport es : src.getEdgeSupports()) dst.addEdgeSupport(new EdgeSupport(es.getId(), es.getPolygonId(), es.getEdgeIndex(), es.getType()));

        // Distributed loads: assume SI (N/m) already, unchanged
        for (DistributedLoad dl : src.getDistributedLoads()) dst.addDistributedLoad(new DistributedLoad(dl.getId(), dl.getPolygonId(), dl.getEdgeIndex(), dl.getWx(), dl.getWy(), dl.getType()));

        return dst;
    }

    /**
     * Convert a PlaneStressResult geometry and displacements back to display units for rendering,
     * keeping stresses (Pa) unchanged.
     */
    public static PlaneStressResult planeStressResultToDisplay(PlaneStressResult si, UnitSettings units) {
        double inv = 1.0 / units.getMetersPerUnit();

        // Scale displacements to display units
        double[] u = si.getDisplacements().clone();
        for (int i = 0; i < u.length; i++) u[i] *= inv;

        // Recreate elements with coordinates in display units
        List<com.treble.feasimulation.model.TriangularElement> srcElems = si.getElements();
        List<com.treble.feasimulation.model.TriangularElement> dispElems = new ArrayList<>();
        for (com.treble.feasimulation.model.TriangularElement te : srcElems) {
            Node[] ns = te.getNodes();
            Node n1 = new Node(ns[0].getId(), ns[0].getX() * inv, ns[0].getY() * inv);
            Node n2 = new Node(ns[1].getId(), ns[1].getX() * inv, ns[1].getY() * inv);
            Node n3 = new Node(ns[2].getId(), ns[2].getX() * inv, ns[2].getY() * inv);
            dispElems.add(new com.treble.feasimulation.model.TriangularElement(
                    te.getId(), n1, n2, n3, te.getMaterialId(), te.getThickness()));
        }

        return new PlaneStressResult(u, si.getElementStresses(), si.getNodeIdToIndex(), dispElems);
    }

    /** Convert a truss result's displacements to display units for rendering. */
    public static TrussSolver.Result trussResultToDisplay(TrussSolver.Result si, UnitSettings units) {
        double inv = 1.0 / units.getMetersPerUnit();
        double[] u = si.getDisplacements().clone();
        for (int i = 0; i < u.length; i++) u[i] *= inv;
        return new TrussSolver.Result(u, si.elementResults, si.maxDisplacement, si.maxStress, si.minStress);
    }

    /** Convert a beam/frame result's displacements to display units for rendering. */
    public static BeamSolver.Result beamResultToDisplay(BeamSolver.Result si, UnitSettings units) {
        double inv = 1.0 / units.getMetersPerUnit();
        double[] u = si.getDisplacements().clone();
        // DOF layout [ux, uy, theta] per node: scale only ux, uy
        for (int i = 0; i < u.length; i += 3) {
            u[i] *= inv;
            if (i + 1 < u.length) u[i + 1] *= inv;
            // rotation (i+2) unchanged
        }
        // Reaction forces are already in SI (N, N·m) and we keep SI in UI; pass through unchanged
        return new BeamSolver.Result(u, si.elementResults, si.getSupportReactions());
    }
}
